version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: star_wars_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/DDL:/docker-entrypoint-initdb.d

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/star_wars_db

volumes:
  postgres_data: